# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  textinterpreterapi:
    image: textinterpreterapi
    build:
      context: .
      dockerfile: ./ShuriApi/textInterpreterApi/textInterpreterApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5080:5080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
